### ISSUE TITLE
kflash_gui flash close 

### ISSUE THREAD

**Issue by jmpty** [sipeed/kflash_gui#7] opened 2019-07-31 00:06 UTC
can.t upload with v1.5.2 on macOS

**Comment by jmpty** [comment] 2019-07-31 00:06
kflash  is error  too
Greeting fail, check serial port (Attempting to use a port that is not open)
bogon:kflash.py tongjinlv$ sudo python kflash.py -p /dev/cu.wchusbserial1430 maixpy_v0.4.0_9_g598f743_minimum.bin 
[INFO] COM Port Selected Manually:  /dev/cu.wchusbserial1430 
[INFO] Default baudrate is 115200 , later it may be changed to the value you set. 
[INFO] Trying to Enter the ISP Mode... 
._
Greeting fail, check serial port (Attempting to use a port that is not open)

**Comment by Neutree** [comment] 2019-07-31 01:56
select board first

**Comment by phjo33** [comment] 2019-08-01 21:25
kflash_gui 1.5.2 when executed clicking on its icon is closing immediately on osx.
It needs to be launched from Terminal, with for example `open /Application/kflash_gui.app`

I had to reduce baudrate to 115200 to have it succeed flashing a firmware too.

**Comment by Neutree** [comment] 2019-08-02 09:12
@phjo33 1.5.2have a bug: it will fail to start when the last file selected not exit, you can delete `.config/kflash_gui/kflash_gui.conf` file and then restart.
and you can try to select `slow mode` but not set baudrate to 115200

**Comment by phjo33** [comment] 2019-08-02 13:20
Deleting kflash_gui.conf does not change a thing. kflash_gui actually never stays opened when launched with double clicking its icon. The reason I tried running it from the terminal was I supposed an error message would appear, which it did not...

I'm pretty sure slow mode did fail previously with default baudrate, but right now I tried and it worked.

**Comment by Neutree** [comment] 2019-08-02 14:44
@phjo33 emmm it's pretty weird but I'm not familiar with macOS, but it works on my mojave

**Comment by jmpty** [comment] 2019-08-03 03:08
thanks  phjo33  open /Application/kflash_gui.app is . ok

**Comment by kotobuki** [comment] 2019-08-06 01:15
Hi,

I have the same issue on a fresh MacBook Pro (15-inch, 2018) running 10.14.6 (18G87). I tried deleting the kflash_gui.conf by executing `rm .config/kflash_gui/kflash_gui.conf` but the result was the same (i.e. the app quits immediately after a double click). To make sure, I confirmed with v1.3.2, v1.5, v1.5.1, and v1.5.2. With all versions, `open /Applications/kflash_gui.app` works for me.

**Comment by dimitre** [comment] 2019-12-17 04:11
I have the same issue of Kflash closing immediatly on macOS. 
invoking directly brings the error
```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/kflash_gui.app.
```
using 1.5.2 (latest for macOS)

**Comment by mdaldoss** [comment] 2020-01-12 21:59
I have managed to fix the launch by running it on the terminal by:
cd folder-where-it-is-the-app 
and
./kflash_gui.app/Contents/MacOS/kflash_gui

hope might be helpful to some .)

**Comment by fanhuafeng** [comment] 2020-05-10 06:34
open terminam and run cmd:
/Applications/kflash_gui.app/Contents/MacOS/kflash_gui
the kflash_gui is run ok!!!

**Comment by Neutree** [comment] 2020-07-30 03:57
upgrade to v1.6.5, issue resolved

**Closed as completed by Neutree** 2020-07-30 03:57 UTC
Labels: pack issue
